# Site settings
title: Empreendedor Juvenil
email: your-email@domain.com
url: https://example.github.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
skills: "O Projeto Primeiro Passo, através da Secretaria do Trabalho e Desenvolvimento Social - STDS, está lançando uma nova linha de ação, o Empreendedor Juvenil, que dará oportunidade aos jovens de 18 a 29 anos de abrirem o seu próprio negócio.
Os participantes do programa receberão 290 horas de capacitação empreendedora, e concorrerão a premiações que vão de R$ 500,00 a R$ 3.000,00 para os melhores Planos de Negócios. Além disso, receberão auxílio do SEBRAE/CE para aprimoramento do Plano de Negócio, bem como o encaminhamento para o microcrédito junto aos agentes do Programa Nacional de Microcrédito Orientado (PNMPO), do Ministério do Trabalho, Banco do Nordeste e Caixa Econômica Federal.
"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: e3cfa9 #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 007938 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Empreendedor Juvenil 
  location: ACESSE
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: flickr
    url: http://flickr.com/vprrn10
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
